[package]
authors = ["Joshua Holmer <jholmer.in@gmail.com>"]
name = "iron_valid"
version = "0.0.1"

[dependencies]
dns-lookup = "^0.2.0"
lazy_static = "^0.2.1"
params = "^0.2.2"
regex = "^0.1.71"

[dev-dependencies]
multipart = "^0.7.0"
